import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/logo.png";
import html2canvas from "html2canvas";

const addBackgroundLogo = (doc) => {
  try {
    /*doc.addImage(
      logo,
      "PNG",
      40,   // X (center-ish)
      80,   // Y
      120,  // width
      120   // height
    );*/
   doc.addImage(logo, "PNG", 60, 100, 90, 90);    
  } catch (e) {
    console.log("Logo load failed");
  }
};

export const downloadInsuranceReport = async (data, refs) => {

  const doc = new jsPDF();
  addBackgroundLogo(doc);

  /* ===== LOGO ===== */
  if (logo) {
    doc.addImage(logo, "PNG", 150, 10, 40, 20);
  }

  /* ===== TITLE ===== */
  doc.setFontSize(20);
  doc.setTextColor(30, 30, 30);
  doc.text("InsurAI Smart Report", 20, 20);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("AI Generated Insurance Summary Report", 20, 26);
  /* ===== USER INFO ===== */
  doc.setFontSize(12);
  doc.text(`Name: ${data.name}`, 20, 40);
  doc.text(`Risk Score: ${data.riskScore}/100`, 20, 48);

  /* ===== TABLE ===== */
  autoTable(doc, {
    startY: 60,
    head: [["Metric", "Value"]],
    body: [
      ["Total Policies", data.policies],
      ["Claims", data.claims],
      ["Coverage", "₹25,00,000"]
    ],
    theme: "grid",
    headStyles: { fillColor: [79, 70, 229] }
  });

  let finalY = doc.lastAutoTable.finalY + 10;

  /* ===== AI RECOMMENDATION ===== */
  doc.setFontSize(14);
  doc.text("AI Recommendation", 20, finalY);

  doc.setFontSize(12);
  doc.text(`Policy: ${data.policy}`, 20, finalY + 10);
  doc.text(`Reason: ${data.reason}`, 20, finalY + 18);
  doc.text(`Confidence: ${data.confidence}%`, 20, finalY + 26);

  /* ===== MULTI CHART EXPORT ===== */

  const charts = [
    { ref: refs?.appointmentRef, title: "Appointment Analytics" },
    { ref: refs?.policyRef, title: "Policy Distribution" },
    { ref: refs?.claimsRef, title: "Claims Status" }
  ];

  for (let chart of charts) {

    if (!chart.ref?.current) continue;

    const canvas = await html2canvas(chart.ref.current);
    const imgData = canvas.toDataURL("image/png");

    doc.addPage();
    addBackgroundLogo(doc);
    doc.setFontSize(16);
    doc.text(chart.title, 20, 20);

    doc.addImage(imgData, "PNG", 15, 30, 180, 100);
 
  }

  /* ===== FOOTER ===== */
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by InsurAI • AI-Powered Insurance Platform",
    20,
    280
  );

  /* ===== DOWNLOAD ===== */
  doc.save("InsurAI_Premium_Report.pdf");
};